format = """
$directory\
$all\
\n$character
"""

right_format = """
$git_branch\
$git_status\
$cmd_duration
"""

# Disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true

[character]
success_symbol = " [](white)"
error_symbol = " [](red)"
vicmd_symbol = "[  ](yellow)"

[hostname]
ssh_only = true
format = "[$hostname](bold blue) "
disabled = false

[cmd_duration]
min_time = 1
format = "[$duration ]($style)[ ](fg:purple)"
disabled = false
style = "fg:white"

[directory]
format = " [ ](fg:purple)[ $path]($style) "
style = "fg:white"
truncation_length = 4
truncate_to_repo=true

[git_branch]
format = "[ ](fg:green) [$branch]($style) "
style = "fg:white"

[git_status]
format="[ ](fg:red)[$all_status$ahead_behind]($style) "
style = "fg:white"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

